#!/usr/bin/env node
/**
 * Vendor the site's web fonts.
 *
 *   npm run fonts
 *
 * The site used to load Inter, Cormorant Garamond, and EB Garamond from
 * Google Fonts, which put a third-party DNS lookup and connection in front of
 * the first paint.  This script asks Google's CSS API for the same faces, keeps
 * the subsets the site's content can use, downloads the woff2 files into
 * fonts/, and writes css/fonts.css with the same @font-face rules pointed at
 * this origin.  unicode-range is preserved, so a visitor still downloads only
 * the subsets their page needs.  Re-run it to change a family or weight; both
 * outputs are checked in and scripts/check-generated.cjs asserts they agree.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FONTS_DIR = path.join(ROOT, 'fonts');
const CSS_FILE = path.join(ROOT, 'css', 'fonts.css');

const FAMILIES = [
  'Inter:wght@400;500;600;700',
  'Cormorant+Garamond:ital,wght@0,600;0,700;1,400',
  'EB+Garamond:wght@700',
];

/* Latin for the site, Greek for the guide's place names and menu words.
   Anything outside these falls back to the system font, as it would have
   from Google for a subset the content never used. */
const SUBSETS = ['latin', 'latin-ext', 'greek', 'greek-ext'];

/* Google serves woff2 only to browsers it knows can use it. */
const BROWSER_UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function parseFontFaces(css) {
  const faces = [];
  const pattern = /\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]*)\}/g;
  for (const match of css.matchAll(pattern)) {
    const [, subset, body] = match;
    const prop = (name) => (body.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1];
    const url = (body.match(/url\(([^)]+)\)/) || [])[1];
    const family = prop('font-family').replace(/^'|'$/g, '');
    if (!url || !/\.woff2$/.test(url)) fail(`Expected a woff2 source for ${family} (${subset})`);
    faces.push({
      subset,
      family,
      style: prop('font-style'),
      weight: Number(prop('font-weight')),
      unicodeRange: prop('unicode-range'),
      url,
    });
  }
  return faces;
}

/* Google answers a variable family such as Inter with one file per subset
   and a rule per requested weight, all naming that same file.  Keep one copy
   and one rule with a weight range, so the browser downloads it once. */
function mergeSharedFiles(faces) {
  const byUrl = new Map();
  for (const face of faces) {
    const merged = byUrl.get(face.url);
    if (merged) {
      merged.weights.push(face.weight);
    } else {
      byUrl.set(face.url, { ...face, weights: [face.weight] });
    }
  }
  return Array.from(byUrl.values(), (face) => {
    const weights = Array.from(new Set(face.weights)).sort((a, b) => a - b);
    const range = weights.length > 1 ? [weights[0], weights[weights.length - 1]] : weights;
    return {
      ...face,
      weightRule: range.join(' '),
      file: `${slug(face.family)}-${face.style}-${range.join('-')}-${face.subset}.woff2`,
    };
  });
}

function fail(message) {
  throw new Error(message);
}

async function main() {
  const query = `family=${FAMILIES.join('&family=')}&display=swap`;
  const response = await fetch(`https://fonts.googleapis.com/css2?${query}`, {
    headers: { 'User-Agent': BROWSER_UA },
  });
  if (!response.ok) fail(`Google Fonts answered ${response.status}`);

  const faces = mergeSharedFiles(
    parseFontFaces(await response.text()).filter((face) => SUBSETS.includes(face.subset))
  );
  if (!faces.length) fail('No @font-face rules were parsed from the Google Fonts CSS');

  fs.rmSync(FONTS_DIR, { recursive: true, force: true });
  fs.mkdirSync(FONTS_DIR, { recursive: true });
  for (const face of faces) {
    const download = await fetch(face.url);
    if (!download.ok) fail(`Could not download ${face.url}: ${download.status}`);
    fs.writeFileSync(path.join(FONTS_DIR, face.file), Buffer.from(await download.arrayBuffer()));
  }

  const order = (face) => [face.family, face.style, face.weights[0], SUBSETS.indexOf(face.subset)];
  faces.sort((a, b) => (order(a) < order(b) ? -1 : 1));

  const rules = faces.map((face) => [
    `/* ${face.family} ${face.style} ${face.weightRule}, ${face.subset} */`,
    '@font-face {',
    `  font-family: '${face.family}';`,
    `  font-style: ${face.style};`,
    `  font-weight: ${face.weightRule};`,
    '  font-display: swap;',
    `  src: url(/fonts/${face.file}) format('woff2');`,
    `  unicode-range: ${face.unicodeRange};`,
    '}',
  ].join('\n'));

  fs.writeFileSync(CSS_FILE, [
    '/* Generated by scripts/fetch-fonts.cjs (npm run fonts). Do not edit by hand:',
    '   the files under fonts/ and these rules are one vendored set. */',
    '',
    ...rules,
    '',
  ].join('\n'));

  console.log(`Vendored ${faces.length} font faces into fonts/ and ${path.relative(ROOT, CSS_FILE)}.`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
